version: '3'
services:
  mysql:
    image: mysql:5.7.24
    ports:
      - 3306:3306  
    volumes:
      - ./config/docker/mysql.d:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
volumes:
  mysql-data:
    driver: local
    